spring.application.name=wallet-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/walletdb}
spring.datasource.username=${DB_USERNAME:wallet_user}
spring.datasource.password=${DB_PASSWORD:wallet_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/init.sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:keychain-wallet-service-super-secret-key-minimum-32-chars-hs256}
